# Playbook to call multiple roels to configure systems
- name: Configure Systems
  hosts: 18.117.82.234
  become: yes
  
  tasks:
  
- name: Call Roles
  hosts: 18.117.82.234
  roles:
    #- hostname
    #- firewalld
    #- ntp-config
    - motd
